PACKAGE_NAME="btusb_mt7902"
PACKAGE_VERSION="git"
MAKE[0]="make KVER=$kernelver"
BUILT_MODULE_NAME[0]=$PACKAGE_NAME
DEST_MODULE_LOCATION[0]="/kernel/drivers/bluetooth/$PACKAGE_NAME"
AUTOINSTALL="yes"
